Connector/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.homeview, name='homepage'),
    
    path('profiles/', views.ProfileList.as_view(), name='profiles'),

    # path('pound/', include(([
    #     path('', .as_view(), name=''),
    #     path('profile/add/', .as_view(), name='profile_add'),
    #     path('profile/<int:pk>/', .as_view(), name='profile_change'),
    #     path('profile/<int:pk>/delete/', .as_view(), name='profile_delete'),
    # ])))
       
    # path('create_profile/', view.CreateProfile.as_view(), name='create_profile')
]

PP4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Connector.urls'), name='Connector_urls'),
    path('accounts/', include('allauth.urls')),
]

Connector/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from cloudinary.models import CloudinaryField
from django.urls import reverse

STATUS = ((0, "Hold"), (1, "Available"), (2, "Booked"), (3, "Transferred to Rescue"), (4, "Rehomed"), (5, "Reclaimed"), (6, "PTS"), (7, "Death Natural Causes"))
URGENCY = ((0, "Red"), (1, "Amber"), (2, "Green"))
NEUTERED = ((0, "Yes"), (1, "No"), (2, "Unknown"))
MICROCHIPPED = ((0, "Yes"), (1, "No"), (2, "Unknown"))
CIRCUMSTANCE = ((0, "Stray"), (1, "Surrender"), (2, "Seized"), (3, "Other"))
GENDER = ((0, "Male"), (1, "Female"))


class User(AbstractUser):
    '''
    From Simple is Better blog - see ReadMe
    '''    
    is_pound = models.BooleanField('pound status', default=False)
    is_rescue = models.BooleanField('rescue status', default=False)


class Profile(models.Model):
    slug = models.SlugField(max_length=200, unique=True)
    profile_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    profile_added = models.DateField(auto_now_add=True)
    last_updated = models.DateField(auto_now=True)
    pound = models.ForeignKey(User, on_delete=models.CASCADE, related_name='dog_profiles')
    dog_breed = models.CharField(max_length=150, unique=False)
    gender = models.IntegerField(choices=GENDER, default=0)
    approx_age = models.CharField(max_length=50, unique=False)
    neutered = models.IntegerField(choices=NEUTERED, default=2)
    microchipped = models.IntegerField(choices=MICROCHIPPED, default=2)
    circumstance = models.IntegerField(choices=CIRCUMSTANCE, default=1)
    pound_entry_date = models.DateField()
    hold_date = models.DateField()
    status = models.IntegerField(choices=STATUS, default=0)
    urgency = models.IntegerField(choices=URGENCY, default=2)

    class Meta:
        ordering = ['-urgency', 'profile_added']
    

    def get_absolute_url(self):
        return reverse('profile_id', kwargs={'pk': self.pk})


RESERVED = ((0, ""), (1, "Reserved for Collection"))


class Reservation(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='reserve_pet')
    status = models.IntegerField(choices=RESERVED, default=0)
    rescue = models.ForeignKey(User, on_delete=models.CASCADE, related_name='Rescue')
    collection_date = models.DateField()
    last_updated = models.DateField(auto_now=True)
    # approved = models.BooleanField('Booking Accepted', default=False)

Connector/forms.py
from .models import Profile, User
from django import forms
from django.contrib.auth.forms import UserCreationForm


class PoundSignUpForm(UserCreationForm):
    '''
    From Simpleisbetterthancomplex.com blog
    '''
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_pound = True
        if commit:
            user.save()
        return user


class RescueSignUpForm(UserCreationForm):
    '''
    From Simpleisbetterthancomplex.com blog
    '''
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_rescue = True
        if commit:
            user.save()
        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('dog_breed', 'gender', 'approx_age', 'neutered', 'microchipped', 'circumstance', 'pound_entry_date', 'hold_date', 'status', 'urgency')

Connector/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic, View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Profile, Reservation
from .forms import ProfileForm


class ProfileList(LoginRequiredMixin, generic.ListView):
    model = Profile
    queryset = Profile.objects.filter(status=0) | Profile.objects.filter(status=1)
    context_object_name = 'profiles'
    template_name = 'index.html'
    paginate_by = 50


def homeview(request):
    return render(request, 'home.html',)


# class CreateProfile(LoginRequiredMixin, generic.CreateView):
#     def get(self, request, *args, **kwargs):

#         return render(
#             request,
#             "create_profile.html",
#             {
#                 "profile_form": ProfileForm(),
#                 # "viewer_access": check_viewer_exists(request)
#             }
#         )


# class ProfileReservation(View):

#     def get(self, request, slug, *args, **kwargs):
#         queryset = Profile.objects.filter(status=0) | Profile.objects.filter(status=1)
#         profile = get_object_or_404(queryset, slug=slug)
#         reservations = Profile.reserve_pet.filter(approved=True)

#         return render(
#             request,
#             "index.html",
#             {
#                 "profile": profile,
#                 "reservation": reservations
#             },
#         )

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Connector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://kit.fontawesome.com/657a87c31d.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'profiles' %}"><span class="brand"><i class="fa-solid fa-paw"></i> Connector</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% else %}
            <a class="navbar-brand" href="{% url 'account_signup' %}"><span class="brand"><i class="fa-solid fa-paw"></i> Connector</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% endif %}
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'profiles' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <p class="pt-3">Logged in as <strong>{{ user.username }}</strong>.
                            <a href="{% url 'account_logout' %}" class="btn btn-light" role="button">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'account_signup' %}" class="btn btn-light" role="button">Register</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'account_login' %}" class="btn btn-primary" role="button">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <!-- <form class="form-inline">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form> -->
            </div>
        </div>
    </nav>

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
    </footer>
</body>

</html>

templates/create_profile.html
{% extends "base.html" %}

{% block content %}


{%endblock%}

templates/home.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Connector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://kit.fontawesome.com/657a87c31d.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'profiles' %}"><span class="brand"><i class="fa-solid fa-paw"></i> Connector</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% else %}
            <a class="navbar-brand"><span class="brand"><i class="fa-solid fa-paw"></i> Connector</span></a>
    </nav>
        <div class="col-6 justify-content-center">
            <a href="{% url 'account_login' %}" class="btn btn-primary" role="button">Login</a>
        </div>
        <div class="col-6 justify-content-center">
            <a href="{% url 'account_signup' %}" class="btn btn-light" role="button">Register</a>
        </div>
            {% endif %}
    </nav>

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
    </footer>
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

<h1>Current Dogs Requiring Placement</h1>
<table class="table table-hover table-bordered table-sm">
    <caption>List of Dogs in Pounds Looking for Placement</caption>
    <tr>
        <th>Profile ID</th><th>Date Added</th><th>Last Updated</th>
        <th>Pound</th><th>Breed</th><th>Gender</th><th>Appox Age</th>
        <th>Neutered</th><th>Microchipped</th><th>Circumstance</th>
        <th>Pound Entry Date</th><th>Hold Date</th><th>Status</th>
        <th>Urgency</th>
    </tr>
   {% for Profile in object_list %}
        <tr>
            <td>{{ Profile.profile_id }}</td>
            <td>{{ Profile.profile_added }}</td>
            <td>{{ Profile.last_update }}</td>
            <td>{{ Profile.pound }}</td>
            <td>{{ Profile.dog_breed }}</td>
            <td>{{ Profile.get_gender_display }}</td>
            <td>{{ Profile.get_approx_age_display }}</td>
            <td>{{ Profile.get_neutered_display }}</td>
            <td>{{ Profile.get_microchipped_display }}</td>
            <td>{{ Profile.get_circumstance_display }}</td>
            <td>{{ Profile.pound_entry }}</td>
            <td>{{ Profile.hold_date }}</td>
            <td>{{ Profile.get_status_display }}</td>
            <td>{{ Profile.get_urgency_display }}</td>
        </tr>
    {% endfor %}
</table>

{%endblock%}